# build and test PayrollProcessor.sln
name: dotnet core - build & test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Build with dotnet
        run: dotnet build api/PayrollProcessor.sln --configuration Release
      - name: Unit Tests
        run: dotnet test api/PayrollProcessor.sln
